    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/panic_test`
normal stuff
bt:    0: backtrace::backtrace::libunwind::trace
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
      backtrace::backtrace::trace_unsynchronized
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/capture.rs:164
   3: backtrace::capture::Backtrace::new
             at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/capture.rs:128
   4: panic_test::main
             at src/main.rs:62
   5: std::rt::lang_start::{{closure}}
             at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libstd/rt.rs:67
   6: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:297
      std::panicking::try
             at src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
   7: std::rt::lang_start
             at /rustc/9912925c254589f58338cb2993163e618475ff75/src/libstd/rt.rs:67
   8: main
   9: __libc_start_main
             at /build/glibc-FUvrFr/glibc-2.28/csu/libc-start.c:308

thread 'main' panicked at 'panic!', src/main.rs:68:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
